### ISSUE TITLE
Error in SHACL Dialog 

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/SPEX#63]
https://spex.zazuko.com/#/?url=https://lindas.admin.ch/query&graph=https://lindas.admin.ch/egad/ric-o&forceIntrospection=false

SHACL Button -> Dialog Choose Turtle drop this intermittent error. 

```
Uncaught (in promise) Error: Invliad concise-term string, prefixes are not allowed to start with an underscore: '_'
    at Object.c1_node (main.js:1394:34)
    at Object.c1 (main.js:1380:28)
    at o._encode_objects (main.js:317:34)
    at o._serialize_collection_object (main.js:442:22)
    at o._encode_objects (main.js:341:40)
    at o._serialize_c3 (main.js:260:27)
    at o._serialize_c4 (main.js:244:20)
    at o.serialize (main.js:273:27)
    at o._transform (main.js:173:19)
    at o._read (_stream_transform.js:177:10)
```

**Comment by BenjaminHofstetter** [comment]
duplicate of #69
